######################################################################
# Automatically generated by qmake (3.1) Mon Jul 14 08:58:47 2025
######################################################################

TEMPLATE = app
TARGET = qt6_project
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += src/MainForm.h \
           plugins/PluginOne/Plugin.h \
           plugins/PluginThree/Plugin.h \
           plugins/PluginTwo/Plugin.h \
           src/Controls/ClientItemView.h \
           src/Controls/FlagCheckBox.h \
           src/Controls/ListBase.h \
           src/Controls/ServerItemListBox.h \
           src/Dialogs/AboutForm.h \
           src/Dialogs/CompareOtbForm.h \
           src/Dialogs/FindItemForm.h \
           src/Dialogs/PreferencesForm.h \
           src/Helpers/FileNameHelper.h \
           src/Helpers/PathHelper.h \
           src/Helpers/Utils.h \
           src/Host/Plugin.h \
           src/Host/PluginCollection.h \
           src/Host/PluginServices.h \
           src/PluginInterface/IPlugin.h \
           src/PluginInterface/Item.h \
           src/PluginInterface/Settings.h \
           src/PluginInterface/Sprite.h \
           src/Properties/settings.h \
           src/Properties/version.h \
           build/plugins/PluginOne/ddf_PluginOne.h \
           build/plugins/PluginThree/ddf_PluginThree.h \
           build/plugins/PluginTwo/ddf_PluginTwo.h \
           build/src/Controls/ddf_ItemEditorControls.h \
           build/src/Dialogs/ddf_ItemEditorDialogs.h \
           build/src/Helpers/ddf_ItemEditorHelpers.h \
           build/src/Host/ddf_ItemEditorHost.h \
           build/src/PluginInterface/ddf_ItemEditorPluginInterface.h \
           build/src/Properties/ddf_ItemEditorProperties.h \
           build/src/ItemEditor_autogen/include_Debug/ui_MainForm.h \
           build/src/PluginInterface/OTLib/ddf_ItemEditorOTLib.h \
           src/PluginInterface/OTLib/Collections/ServerItemList.h \
           src/PluginInterface/OTLib/OTB/OtbReader.h \
           build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/ui_AboutForm.h \
           build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/ui_CompareOtbForm.h \
           build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/ui_FindItemForm.h \
           build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/ui_PreferencesForm.h \
           build/src/PluginInterface/OTLib/Collections/ddf_ItemEditorOTLibCollections.h \
           build/src/PluginInterface/OTLib/OTB/ddf_ItemEditorOTLibOTB.h \
           build/src/PluginInterface/OTLib/Server/ddf_ItemEditorOTLibServer.h \
           build/src/PluginInterface/OTLib/Utils/ddf_ItemEditorOTLibUtils.h \
           src/PluginInterface/OTLib/Server/Items/ServerItem.h \
           src/PluginInterface/OTLib/Server/Items/ServerItemFlag.h \
           build/src/PluginInterface/OTLib/Server/Items/ddf_ItemEditorOTLibServerItems.h \
           /src/Helpers/PathHelper.h \
           /src/Helpers/FileNameHelper.h \
           /src/Helpers/Utils.h \
           /src/Host/PluginServices.h \
           /src/Host/Plugin.h \
           /src/Host/PluginCollection.h \
           /src/PluginInterface/OTLib/Server/Items/ServerItemFlag.h \
           /build/src/ItemEditor_autogen/include_Debug/ui_MainForm.h \
           /src/PluginInterface/IPlugin.h \
           /src/PluginInterface/Settings.h \
           /src/PluginInterface/Sprite.h \
           /src/PluginInterface/Item.h \
           /build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/ui_AboutForm.h \
           /build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/ui_CompareOtbForm.h \
           /build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/ui_FindItemForm.h \
           /build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/ui_PreferencesForm.h \
           /build/src/ItemEditor_autogen/include_Debug/EWIEGA46WW/moc_MainForm.cpp \
           /build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/EWIEGA46WW/moc_AboutForm.cpp \
           /build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/EWIEGA46WW/moc_CompareOtbForm.cpp \
           /build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/EWIEGA46WW/moc_FindItemForm.cpp \
           /build/src/Dialogs/ItemEditorDialogs_autogen/include_Debug/EWIEGA46WW/moc_PreferencesForm.cpp
FORMS += src/MainForm.ui \
         src/Dialogs/AboutForm.ui \
         src/Dialogs/CompareOtbForm.ui \
         src/Dialogs/FindItemForm.ui \
         src/Dialogs/PreferencesForm.ui
SOURCES += test_helpers.cpp \
           test_plugin_system.cpp \
           test_serveritemlist.cpp \
           /test_serveritemlist.cpp \
           src/main.cpp \
           src/MainForm.cpp \
           plugins/PluginOne/Plugin.cpp \
           plugins/PluginThree/Plugin.cpp \
           plugins/PluginTwo/Plugin.cpp \
           src/Controls/ClientItemView.cpp \
           src/Controls/FlagCheckBox.cpp \
           src/Controls/ListBase.cpp \
           src/Controls/ServerItemListBox.cpp \
           src/Dialogs/AboutForm.cpp \
           src/Dialogs/CompareOtbForm.cpp \
           src/Dialogs/FindItemForm.cpp \
           src/Dialogs/PreferencesForm.cpp \
           src/Helpers/FileNameHelper.cpp \
           src/Helpers/PathHelper.cpp \
           src/Helpers/Utils.cpp \
           src/Host/Plugin.cpp \
           src/Host/PluginCollection.cpp \
           src/Host/PluginServices.cpp \
           src/PluginInterface/Item.cpp \
           src/PluginInterface/Settings.cpp \
           src/PluginInterface/Sprite.cpp \
           src/Properties/settings.cpp \
           src/Properties/version.cpp \
           build/src/ItemEditor_autogen/mocs_compilation_Debug.cpp \
           build/CMakeFiles/4.0.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/src/Controls/ItemEditorControls_autogen/mocs_compilation_Debug.cpp \
           build/src/Dialogs/ItemEditorDialogs_autogen/mocs_compilation_Debug.cpp \
           build/src/Helpers/ItemEditorHelpers_autogen/mocs_compilation_Debug.cpp \
           build/src/Host/ItemEditorHost_autogen/mocs_compilation_Debug.cpp \
           build/src/PluginInterface/ItemEditorPluginInterface_autogen/mocs_compilation_Debug.cpp \
           build/src/Properties/ItemEditorProperties_autogen/mocs_compilation_Debug.cpp \
           src/PluginInterface/OTLib/Collections/ServerItemList.cpp \
           src/PluginInterface/OTLib/OTB/OtbReader.cpp \
           build/src/PluginInterface/OTLib/ItemEditorOTLib_autogen/mocs_compilation_Debug.cpp \
           build/src/Properties/.qt/rcc/qrc_application_resources.cpp \
           build/src/Properties/.qt/rcc/qrc_application_resources_init.cpp \
           build/src/Properties/ItemEditorProperties_autogen/EWIEGA46WW_Debug/qrc_application.cpp \
           src/PluginInterface/OTLib/Server/Items/ServerItem.cpp \
           src/PluginInterface/OTLib/Server/Items/ServerItemFlag.cpp \
           build/src/PluginInterface/OTLib/Collections/ItemEditorOTLibCollections_autogen/mocs_compilation_Debug.cpp \
           build/src/PluginInterface/OTLib/OTB/ItemEditorOTLibOTB_autogen/mocs_compilation_Debug.cpp \
           build/src/PluginInterface/OTLib/Server/ItemEditorOTLibServer_autogen/mocs_compilation_Debug.cpp \
           build/src/Properties/ItemEditorProperties_autogen/include_Debug/EWIEGA46WW/qrc_application_CMAKE_.cpp \
           build/src/PluginInterface/OTLib/Server/Items/ItemEditorOTLibServerItems_autogen/mocs_compilation_Debug.cpp
RESOURCES += src/Properties/application.qrc \
             build/src/Properties/.qt/rcc/application_resources.qrc
